# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Amanda Escalona | Escritora
email: amandaescalona30@gmail.com
description:  >- # this means to ignore newlines until "baseurl:"
  🦉🤓Nerd freelancer: Redactora de contenido, copy writer, community manager, escritora por las noches 🦇 y lectora ávida ⚡. ¡Lista para generar contenido persuasivo que aumente tus ventas!🖤

bio:  "¿Ratón de biblioteca? Es posible, tanto así que he vivido gran parte de mi vida con un libro debajo del brazo. Entonces quise hacer de la literatura mi vida y estudié letras en la Universidad Católica Andrés Bello. Luego de eso me encontré, de un golpe inesperado, con el marketing, entonces uní mi amor por escribir, con el amor por la tecnología y la comunicación, y me convertí en mi yo de ahora: Redactora de contenido, community manager, escritora por las noches y lectora ávida.
He escrito de todo un poco, desde
tecnología, hasta medicina y psicología infantil. Asimismo, me gusta investigar, estudiar el tema que estoy
trabajando y escribir con la mayor fidelidad posible, es decir, siempre hago un estudio de vocabulario o
terminología antes de realizar el trabajo."

logo: 
#baseurl: "/blog" # the subpath of your site, e.g. /blog
#url: "https://localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
url: "https://amandaescalona.github.io" # the base hostname & protocol for your site, e.g. http://example.com

#social 
lang: es_ES
social:
  name: Amanda Escalona
  links:
    - instagram: https://www.instagram.com/nadhiadarkworld/
    - linkedin: https://www.linkedin.com/mwlite/in/amanda-escalona-370a29145
    - github: https://github.com/amandaescalona
    - urania: 


#path: "/:basename"
twitter_username: nadhia
github_username:  amandaescalona
instagram_username: urania.digital

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
# Build settings
theme: minima

permalink: /:title

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
